#!/bin/bash
set -e -u
set -o pipefail

TRY_KEYGEN=1
for KEY in /etc/ssh/ssh_host_*_key.pub; do
	ssh-keygen -l -f "$KEY" | cut -d ' ' -f '1,3-'
	for HASH in md5 sha256; do
		printf "   "
		if ! ssh-keygen -l -E $HASH -f "$KEY" 2>/dev/null | cut -d ' ' -f 2; then
			if [[ "$HASH" == "md5" ]]; then
				echo -n "MD5:"
				#ssh-keygen -l -f "$KEY" | cut -d ' ' -f 2
				cut -d ' ' -f 2 "$KEY" | base64 -d | openssl dgst -c -md5 -hex | cut -d ' ' -f 2
			elif [[ "$HASH" == "sha256" ]]; then
				echo -n "SHA256:"
				cut -d ' ' -f 2 "$KEY" | base64 -d | openssl dgst -c -sha256 -binary | base64 | tr -d '='
			else
				echo "$HASH:?"
			fi
		fi
	done
	echo
done
