#!/bin/bash
set -e -u
set -o pipefail

if [[ -n "${1:-}" ]]; then
	echo "usage: $0"
	echo "Show ssh server host key fingerprints as MD5 and SHA256"

	if [[ "${1:-}" == @(-h|--help) ]]; then
		exit 0
	else
		exit 1
	fi
fi

for KEY in /etc/ssh/ssh_host_*_key.pub; do
	ssh-keygen -l -f "$KEY" | cut -d ' ' -f '1,3-'
	for HASH in md5 sha256; do
		printf "   "
		# We first try `ssh-keygen -E`
		if ! ssh-keygen -l -E $HASH -f "$KEY" 2>/dev/null | cut -d ' ' -f 2; then
			# If that didn't work we try openssl as a fallback
			if [[ "$HASH" == "md5" ]]; then
				printf "MD5:"
				cut -d ' ' -f 2 "$KEY" | base64 -d | openssl dgst -c -md5 -hex | cut -d ' ' -f 2
			elif [[ "$HASH" == "sha256" ]]; then
				printf "SHA256:"
				cut -d ' ' -f 2 "$KEY" | base64 -d | openssl dgst -c -sha256 -binary | base64 | tr -d '='
			else
				echo "$HASH:<???>"
			fi
		fi
	done
	echo
done
